testing dockerhub push

diff --git a/.github/workflows/deploy_storyspark.yml b/.github/workflows/deploy_storyspark.yml
--- a/.github/workflows/deploy_storyspark.yml
+++ b/.github/workflows/deploy_storyspark.yml
@@ -242,6 +242,51 @@ jobs:
         fi
         echo "image_ref=${REPO_PATH}@${DIGEST}" >> $GITHUB_OUTPUT
 
+  docker-push-2:
+    runs-on: ubuntu-latest
+    needs: [setup, docker-build]
+    outputs:
+      image_ref: ${{ steps.get_digest.outputs.image_ref}}
+    permissions:
+      contents: read # Need read permission for checkout
+    
+    steps:
+    - name: Checkout repository
+      uses: actions/checkout@v4
+
+    - name: Download image artifact
+      uses: actions/download-artifact@v4
+      with:
+        name: ${{ needs.docker-build.outputs.saved_image_filename }}
+        path: .
+
+    - name: Load image into Docker
+      run: |
+        docker load -i ${{ needs.docker-build.outputs.saved_image_filename }}
+
+    - name: Login to Docker Hub
+      uses: docker/login-action@v2
+      with:
+        username: ${{ secrets.STORYSPARK_DOCKERHUB_USERNAME }}
+        password: ${{ vars.STORYSPARK_DOCKERHUB_TOKEN }}  
+        
+    - name: Push the Docker image
+      run: |
+        docker push ${{ needs.setup.outputs.image_name  }}
+
+    # - name: Get pushed image digest
+    #   id: get_digest
+    #   run: |
+    #     IMAGE_TAG="${{ needs.setup.outputs.image_tag }}"
+    #     REPO_PATH=${{ needs.setup.outputs.image_repo_path }}
+    #     DIGEST=$(gcloud artifacts docker images describe "${REPO_PATH}:${IMAGE_TAG}" \
+    #       --project="${{ vars.STORYSPARK_GCP_PROJECT_ID }}" --format='get(image_summary.digest)')
+    #     if [ -z "${DIGEST}" ]; then
+    #       echo "Failed to find digest for ${REPO_PATH}:${IMAGE_TAG}" >&2
+    #       exit 1
+    #     fi
+    #     echo "image_ref=${REPO_PATH}@${DIGEST}" >> $GITHUB_OUTPUT
+
 #-------------------------------------------------------------------------------------------------------------------------
 
   terraform-plan: # This job will run on PRs and main branch pushes to generate the plan
